name: dropletUtils
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - r-base=4.3.1
  - r-matrix=1.6_1
  - r-argparse=2.2.2
  - bioconductor-dropletutils=1.20.0
  - bioconductor-scater=1.28.0
  - bioconductor-scran=1.28.1
  - bioconductor-biocparallel=1.34.2
  - bioconductor-scuttle=1.10.1